"""add phone number

Revision ID: 4ceef25e10bd
Revises: 387e7e86d0b4
Create Date: 2024-12-21 22:05:43.945642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ceef25e10bd'
down_revision: Union[str, None] = '387e7e86d0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('posts', sa.Column('title', sa.String(), nullable=False))
    # op.drop_column('posts', 'Title')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # op.add_column('posts', sa.Column('Title', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_column('posts', 'title')
    # ### end Alembic commands ###
